import React, { useEffect, useRef, useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X, Terminal } from 'lucide-react';
import { useIsMobile } from '@/hooks/use-mobile';

/**
 * SpidrSystem — a "system terminal" news/patch feed anchored bottom-right of the
 * home page. Collapsed: a one-line ticker. Expanded: a scrollable panel of
 * announcements with a typewriter intro on the newest note.
 *
 * Data: ships with mock notes so it renders instantly, then tries to refresh
 * from GET {API}/system/news. A glowing "Spider-Sense" badge appears when there
 * are unread notes (tracked by the newest id in localStorage).
 */

const MOCK_NEWS = [
  { id: 'p1953', title: 'Patch 1.9.53 — Signals tab peek-safe + ghost DMs really gone', date: '2026-07-21', type: 'FIX', description: 'Fixes two related bugs in the "Signals" message-request inbox on the Friends panel. First: the tab was querying is_read: false, which meant a request from a stranger vanished the moment you peeked at their DM — no accept, no block, no way back. Semantic was wrong; the tab is "pending requests from non-friends", not "unread DMs from strangers". The query now drops the is_read filter and instead pulls the 200 most recent DMs to you, deduped by sender and filtered against your friend list, so peeking no longer erases the request. Second: the server-side ghost-user filter on GET /direct-messages was a no-op — filterOrphans used .some() (row kept if ANY participant is live), and since the caller IS a live participant, every DM row survived even when the other side had been deleted. Flipped to .every() so a DM row now needs BOTH participants alive to render, which drops ghost-participant DMs from Jump Back In, the DirectMessages panel, and Signals in one shot. Also added a disabled state on the Accept / Sever buttons while the mutation is in flight so a double-click cannot create duplicate Friend rows.' },
  { id: 'p1952', title: 'Patch 1.9.52 — Ghost members purged + fly-catch DMs go real', date: '2026-07-21', type: 'FIX', description: 'Two piles of ghost data cleaned up server-side. First: deleted accounts used to leave "ghost members" hanging in every server\'s member list — Electron sidebars kept rendering avatars for users whose profiles no longer existed. The admin sweep-orphans job now prunes Server.members[] and Server.banned_users[] and deletes any server whose owner no longer exists, mirroring the Friend / DirectMessage / GroupChatMember cleanup it already did. GET /servers and GET /servers/:id also strip ghost members live on read, so a deletion clears from every sidebar on the next fetch without waiting for the sweep. A one-time sweep against production removed 4 orphan friends, 81 orphan DMs, 4 ghost group-chat members, 2 ghost server members, and 1 owner-less server. Second: the "You caught the fly! +N Biomass" system DM was being fabricated on the client with a fake spidr-ai sender, which landed the message in a self-DM thread instead of the real Spidr System account. The catch is now logged server-side via sendSystemDM inside /biomass/fly — one source of truth, real system sender, fire-and-forget so a DM write can\'t fail the reward. A scripts/purge-fake-fly-dms.js dry-run/--delete helper is included to sweep the fabricated rows out of production.' },
  { id: 'p1951', title: 'Patch 1.9.51 — Installers ready to ship', date: '2026-07-20', type: 'UPDATE', description: 'Spidr is now packaged for real distribution — Windows .exe, macOS .dmg for both Intel and Apple Silicon, and Linux AppImage plus .deb. The full electron-builder configuration is production-ready in package.json: proper artifact naming (product-version-os-arch), macOS hardened runtime + entitlements + social-networking category, Windows NSIS installer with configurable install location plus a portable exe, Linux AppImage plus deb with correct category and StartupWMClass. The missing Linux icon.png is generated from the transparent mascot at 512x512 with proper alpha, complementing the existing icon.icns and icon.ico for macOS and Windows. A .env.production file bakes the current Render API URL into installer builds, with a .env.production.template ready for anyone forking to point at their own backend. Distribution architecture: a new .github/workflows/build-installers.yml GitHub Actions workflow runs one job per OS on that OS\'s native runner — you cannot cross-build macOS from Linux (Apple\'s toolchain requirement) so CI is the only clean path. Push a git tag like v1.0.0 and CI produces all three platforms\' installers and attaches them to a GitHub Release automatically; use the release URL as your download page. BUILD_INSTALLERS.md at the repo root documents every path (CI, per-OS local, code signing for public releases, auto-update, troubleshooting). What still requires paid infrastructure: Windows code signing (~$300/yr for a real cert, users hit SmartScreen otherwise) and macOS notarization ($99/yr Apple Developer account, users hit Gatekeeper otherwise) — both work for internal distribution unsigned but the docs explain how to plug in production signing once you\'re ready.' },
  { id: 'p1950', title: 'Patch 1.9.50 — Voice & Audio Uplink is live', date: '2026-07-20', type: 'UPDATE', description: 'Full pro-grade audio controls, in-call and in Settings. Every voice call now carries three processing filters mapped straight to the native WebRTC constraints — Noise Suppression (kills fan hum and keyboard clicks), Echo Cancellation (prevents mic-to-speaker feedback), Auto Gain Control (normalizes your input volume). All three toggle live during a call via a new dock button in the expanded call deck (green gear icon next to Deafen) — click it and a floating Voice & Audio Uplink panel appears with the mic device selector, a live input-level meter, and every processing filter. Changing your mic device now swaps INSTANTLY via RTCRtpSender.replaceTrack — no rejoin, no drop, no ICE round-trip, no perceptible glitch on the receiving side. The paste blueprint\'s pro-tier feature: a Voice Activity Threshold slider (0-100). At 0 the mic always transmits (default), but crank it up and the mic soft-mutes whenever your level sits below the gate, silencing hum and typing between sentences — the panel shows a yellow tick on the level meter at your threshold so you can dial it just above your ambient noise. Same controls duplicated in Settings → Voice & Video for pre-call configuration. Everything routes through mediaDevicePrefs (localStorage) so it survives restarts and applies before any profile fetch resolves.' },
  { id: 'p1949', title: 'Patch 1.9.49 — Sidebar ring fires for everyone', date: '2026-07-20', type: 'FIX', description: 'Only the local user\'s speaking ring was lighting up in the servers sidebar; remote peers stayed dark even when speaking. The local ring was working via the always-on pill broadcaster (spidr-call-voice-activity); remote users depended on their VoiceTile firing spidr-tile-speaking, but the tile\'s detector was gated by a deckHidden flag that turned it off whenever the call deck was minimized (which it is any time the user is viewing anything other than the expanded call — including the sidebar itself). Fixed two ways: the tile\'s detector now runs whenever a stream exists (safe now that shared audio sources are ref-counted from the last patch), AND an invisible PeerSpeakingBroadcaster component now lives next to the audio spine at VoiceChannel\'s root — one always-on detector per remote peer, publishing the same event. Independent of tile mounts, deck state, or any parent visibility. Every talking user\'s sidebar avatar now pulses red the moment they start speaking.' },
  { id: 'p1948', title: 'Patch 1.9.48 — Audio survives every screen share', date: '2026-07-20', type: 'FIX', description: 'Traced why voice audio broke and why the streamer went deaf during screen shares. Root cause: WebRTC has a hard rule I violated — you can only create ONE MediaStreamAudioSourceNode per MediaStream. A second createMediaStreamSource call on the same stream causes Chrome to silently detach the audio element playback pipeline. The sidebar speaking broadcast I added last patch created a duplicate source on every remote MediaStream (on top of the per-tile speaking detector that already had one). And VoiceEqualizer — the bar-visualizer that mounts the moment someone starts talking — had been quietly opening a THIRD source on the same stream for months. Three analysers per remote stream, all fighting Chrome for the pipeline, audio dying whenever any of them mounted or unmounted. Fixed at the plumbing layer: sharedAudioContext now exports getSharedSource / releaseSharedSource — a ref-counted registry that guarantees exactly ONE MediaStreamAudioSourceNode per MediaStream, no matter how many analysers want to observe it. The speaking detector, the equalizer, and the sidebar broadcast all route through it. The sidebar user-speaking event now reuses each tile\'s existing detector output (spidr-tile-speaking) instead of opening a parallel tap, so no new stream taps were added to fix the sidebar animation. Audio should survive screen share start/stop, mute toggles, tile mounts, and every other event that previously killed it.' },
  { id: 'p1947', title: 'Patch 1.9.47 — Friends route unblanked + red speaking ring', date: '2026-07-19', type: 'FIX', description: 'Emergency hotfix on the /friends white-screen crash from patch 1.9.46. Root cause: the no-answer timer effect I added referenced voiceSessions inside its dependency array — but the dependency array is evaluated inline at render time, and voiceSessions was declared a hundred and eighty lines below via useQuery. Every render hit the Temporal Dead Zone before initialization and crashed the whole page (the ReferenceError, cannot access ae before initialization in the console — ae is the minified name for voiceSessions). Fixed by moving the effect BELOW the useQuery declaration so its identifier exists when the deps array runs. A full app-wide sweep for the same pattern in every other file came back clean. Sidebar talking ring: green swapped to red to match the Spidr accent — pulsing crimson glow around the avatar and a shadow flare at 85 percent alpha instead of the wrong green.' },
  { id: 'p1946', title: 'Patch 1.9.46 — Voice presence, missed calls, invite fix', date: '2026-07-18', type: 'UPDATE', description: 'Three-part sweep from the QA blueprint. Sidebar speaking animation: each voice-channel roster avatar in the servers sidebar now pulses green when that user is actually talking, and their name brightens from muted gray to bold white — driven live by the per-peer analysers already sampling for the active-speaker PiP swap, broadcast at 5Hz to the sidebar. Missed-call notifications: a schema-first field pair on both DirectMessage and GroupChatMessage (is_missed_call + missed_call_reason + caller identity), server handlers on call:decline and call:cancel now write a real durable row on the correct chat lane (DM or group), the DM caller side gets a 60s no-answer timer that fires the same flow if nobody picks up, MessageItem renders these rows as a centered red-tinted alert bubble with a phone-missed icon and different wording per reason (You missed a call from X vs. X declined your call vs. X didn\'t answer). Both DMs and group chats inherit the render for free. Server invite white-screen fix: traced the crash — the /join/:code route was gated behind isAuthenticated so logged-out visitors were bounced to login and lost the invite code entirely. Fixed at three layers: server /servers/lookup/:code is now public (invite previews should be visible to everyone), the client route is public too, and logged-out Accept clicks stash the invite code and route back to /join/:code automatically after login — the invite survives the auth funnel now.' },
  { id: 'p1945', title: 'Patch 1.9.45 — WebRTC audio hoisted permanently', date: '2026-07-16', type: 'FIX', description: 'Fixed the deafness-during-share bug at its ROOT this time. Traced the audio elements in VoiceChannel — they were nested inside the scrollable stage container, which is exactly the region that swaps layouts when someone starts sharing their screen. When the layout swapped, React unmounted the audio elements during reconciliation and the streamer stopped hearing everyone else instantly. Every remote voice audio element AND every remote screen-share audio element now lives at the ROOT of the VoiceChannel tree, above every conditional layout branch (focus/spider/theater/streaming); nothing about the UI below can ever unmount them again. Mobile stream visibility: caught the missing playsInline on the local screen-share preview and both local camera renders — without it iOS silently hijacks the stream into fullscreen media playback which fails and shows a black frame. Every video and audio element in the call now carries playsInline. Mobile stage sizing: previously stage and chat sidebar both had flex-1 in the column layout, so on a phone the stage collapsed to a tiny slice; forced the stage to a 45vh minimum on mobile so streams have real vertical space to render. Screen-audio quality: getDisplayMedia was requesting audio: true, letting the browser apply voice filters that mangle game and music audio — now requests audio with echo cancellation, noise suppression, and auto-gain-control OFF so streamed audio reaches viewers with its full spectrum. Reminder for viewers on Chrome/Edge: you must check Share tab audio or Share system audio in the browser share picker or no sound will ever reach the room, regardless of code.' },
  { id: 'p1944', title: 'Patch 1.9.44 — AI Scribe transcribes voice messages', date: '2026-07-15', type: 'UPDATE', description: 'The AI Scribe pane on voice-message capsules is live — tap the sparkles on any voice note and Spidr AI transcribes it to text. Real speech-to-text via Whisper, proxied through the Spidr server: transcription is lazy (nothing is transcribed until someone actually opens the Scribe, so silent capsules cost nothing), cached per-URL on the server (the second person to open a note gets the transcript instantly, no re-processing), and capped at 25MB of audio. The pane shows a live Transcribing indicator while working, renders the transcript in place of the old placeholder when done, and if the server is missing its speech key it says so plainly instead of pretending. Works everywhere capsules render: DMs, group chats, and server channels. Server setup note: requires OPENAI_API_KEY in the server env (documented in .env.example) — Whisper is an OpenAI service; chat AI continues to run on whichever provider you have configured.' },
  { id: 'p1943', title: 'Patch 1.9.43 — Mobile streams, stream audio, share stability', date: '2026-07-11', type: 'FIX', description: 'Three compounding streaming bugs down. Mobile viewers could not see streams AT ALL — the in-call chat sidebar was a fixed-width column beside the stage, and on a phone it consumed the entire viewport, squeezing the stage (tiles, cameras, screen shares) to zero width; you saw the roster and chat and nothing else. The layout now stacks on phones: stage first with the stream fully visible, chat below. Stream audio was inaudible for EVERYONE, every platform — remote screen-share videos are muted for autoplay policy, and the system-audio track the sharer forwards died with them. Every remote share now pairs a dedicated hidden audio element that obeys deafen, your chosen output device, and the mobile tap-to-enable overlay just like any voice stream. And the big one: starting a screen share could kill the STREAMER\'s incoming audio — share start/stop triggers WebRTC renegotiation, which can blip connections into a transient disconnected state that self-heals in a second; the old handler tore the peer down INSTANTLY on that blip, dropping their audio and video mid-share on both sides. Transient disconnects now get a four-second grace before teardown (hard failures still tear down immediately). One infrastructure reminder for full cross-network reliability, especially phone-to-desktop: set the TURN relay env on the server (TURN_URLS / TURN_USERNAME / TURN_CREDENTIAL — see .env.example); STUN alone cannot cross strict mobile carrier NATs.' },
  { id: 'p1942', title: 'Patch 1.9.42 — Biomass white screen fixed', date: '2026-07-10', type: 'FIX', description: 'The Biomass page crashed on load with a blank screen — the console told the whole story: ReferenceError, currentUser is not defined. The page\'s wallet and profile queries referenced currentUser for the user id, but the component never pulled it from the app shell context — the one hook call every other page makes was missing here. One line (plus its import) and the page renders: wallet balance, daily claim, shop, inventory, and equips all come back. A full identifier sweep of the page confirmed nothing else on it references an undefined name.' },
  { id: 'p1941', title: 'Patch 1.9.41 — QA blueprint sweep', date: '2026-07-10', type: 'UPDATE', description: 'Six-item QA pass. Group chat pfps now show in the Friends page group list — the rows were reading the legacy icon_url field while uploads save to avatar_url, so every group with a custom picture rendered the fallback glyph. Profile privacy: Vibe Check and Neon Sign each gain an eye toggle on your own profile — hide either from visitors (you still see them dimmed so the toggle stays reachable), persisted to your profile with a schema-first field. The APEX crest got its clean-cut master art (the previous export had a white background baked into the shield edges) — nameplate badges, the dock button, and the Settings trigger all wear the crisp version, and the nameplate badge is confirmed a static crest with the gold aura, not a dead button. Mobile voice calls: remote audio elements now carry playsInline and detect when iOS Safari or mobile Chrome block autoplay — instead of joining a call you can\'t hear, a TAP TO ENABLE CALL AUDIO pill appears and one tap unlocks every stream plus the audio engine. Also swept the last content emojis out of the profile widgets. Verified already-working against the blueprint\'s diagnoses: the minimized pill\'s participant strip (queries live voice sessions per call type — never mapped only yourself), and screen-sharing THE WEB through the Electron window picker.' },
  { id: 'p1940', title: 'Patch 1.9.40 — The square is dead', date: '2026-07-09', type: 'FIX', description: 'Found the real root cause of the persistent dark square behind the Spidr logo: the public/logo.png file itself had the background BAKED INTO ITS PIXELS — fully opaque, no transparency anywhere. Every one of the twelve-plus components rendering SpiderLogo (the AI welcome hero, the left rail, the dock, login, mobile menu, bot messages) was faithfully displaying a poisoned source file, which is why component-level fixes never made the square disappear. The file has been replaced with the true transparent master art — same spider, real alpha channel — so every logo in the app now renders clean, everywhere, at once. The APEX shield badge also gains a dedicated dock button: the badge itself sits in the floating dock with a gold hover glow, one tap routes to Settings and auto-opens the APEX store via a new ?apex=1 deep link. And the last emoji stragglers in Spidr AI (the greeting line and Catch Me Up message text) are gone — the persona tab icons shipped in 1.9.39 and are confirmed in this build.' },
  { id: 'p1939', title: 'Patch 1.9.39 — AI identity polish + Jump Back In everywhere', date: '2026-07-09', type: 'FIX', description: 'Spidr AI finally looks like Spidr everywhere. The AI panel\'s assistant avatar dropped the solid red circle with the geometric logo for the real transparent mascot — the art floats free with a soft red glow, no background tile, no square crop. The persona tabs shed their OS emojis for proper vector iconography: Spidr wears its bespoke spider sigil, Rogue a purple skull, Ghost the ghost mark, Hype a flame, Sage a leaf, Noir the venetian mask — and Catch Me Up gets a golden bolt. Each tinted to its persona. Jump Back In (recent DMs + group chats) now shows on EVERY screen size: the right rail stays on wide desktop displays, and below that width the same panel renders in the main column — one shared component, so the two mounts can never drift apart. Phone, tablet, laptop, ultrawide: your conversations are one tap from home everywhere. Also re-verified end-to-end this patch: Save to Collection on THE WEB (picker state, mutations, schema, route ownership, and error toasts all confirmed wired), the Apex badge button in Settings, and the mascot as the AI\'s avatar across chat surfaces — if any of these look wrong on your screen, you are running a previous deploy; check this patch number appears in Spidr System after updating.' },
  { id: 'p1938', title: 'Patch 1.9.38 — Real brand art everywhere', date: '2026-07-09', type: 'UPDATE', description: 'Three logo drop-ins across the app. The homepage welcome slab now wears the real Spidr mascot art — the same chrome ring, but the flat geometric SpiderLogo swapped for the full illustrated crest with the red fangs and glowing eyes. Spidr AI\'s avatar upgrades everywhere it appears (voice tiles, chat bubbles, message headers, DM cards, server rooms) via the single SPIDR_AI_AVATAR export the AI already routes through — one file swap, six surfaces updated. And the Apex button in Settings drops the mini icon-plus-text combo for the full APEX TIER shield badge as the button itself, with a soft gold hover aura. No mocks, no filler — the crest art you sent is the button.' },
  { id: 'p1937', title: 'Patch 1.9.37 — Real names in Jump Back In', date: '2026-07-08', type: 'FIX', description: 'The "Node" labels in Jump Back In were not mocked — they were real DMs whose sender name resolution had run out of fallbacks. Root cause: DMs YOU send stamp sender_name but never stamped recipient_name (a schema gap from before recipient denormalization existed), so any conversation on the list where you sent the last message had no name to show and hit the fallback string. Fixed at both send call-sites — outgoing DMs now stamp recipient_name and recipient_avatar from the active conversation, matching the sender denorm pattern. Jump Back In also gained a real-time backfill: for old rows still missing recipient info, it now resolves the friend from your friend list (name + avatar) instead of showing the fallback. Old "Node" rows will fix themselves on your next reply to that thread, or immediately for anyone in your friend list.' },
  { id: 'p1936', title: 'Patch 1.9.36 — Delete accounts, admin console, seven live bugs', date: '2026-07-08', type: 'UPDATE', description: 'Big release-prep sweep. Account self-service: Settings → Privacy → Danger Zone lets any user permanently delete their account. The delete cascade runs server-side and erases everything they touched — profile, wallet, DMs (sent and received), messages, clips, comments, feed posts, friends, notifications, voice sessions, installed modules, saved audio, custom bots, plus their servers and every group membership. Type DELETE to confirm; no recovery. Platform admin console lives at /admin, gated by User.role === admin. Admins see every user with search across username/email/name, can ban with a reason (the login route already blocks banned users), unban, grant/revoke admin, and permanently delete another account through the same cascade. Every destructive action requires typed confirmation. Bugs fixed that were breaking release: (1) the notification bell fired on YOUR OWN sent DMs because dm:new was broadcast to the whole conversation room including the sender with an empty payload the client could not self-skip — dm:new now goes only to the recipient with proper sender_id in the payload, and a new dm:sent event tells the sender it landed without notifying them. (2) REST-posted server messages never emitted message:new, so @-mentions and channel replies never lit the bell — the route now emits properly. (3) The Biomass page rendered but nothing worked because Mongoose Maps serialize as empty objects by default, so inventory lookups always found zero items — the wallet route now flattens the Map before responding. (4) Online/Invisible/Busy/Away picker looked empty because entities.UserProfile.update was silently failing (swallowed catch) — status changes now surface errors, auto-create the profile row if missing, and invalidate every caching layer that displays presence. (5) SPIDR WEB heads in the friends page had only toggle-pin on right-click — now open the standard tactical menu with View Profile, Send Message, Pin/Unpin, Remove Friend, Block, Copy ID for DMs and Open Group + Pin/Unpin for groups. (6) Spidr AI stayed in voice channels after the last human left (and kept talking) — now auto-leaves the moment humans hit zero, with local TTS cancelled instantly so audio stops the moment the room empties.' },
  { id: 'p1935', title: 'Patch 1.9.35 — Voice hardening + homepage rail + release polish', date: '2026-07-08', type: 'UPDATE', description: 'Nine fixes and refinements packed for release. Voice calls: the deafen headphones button is now in the expanded call dock (was only reachable from the pill); screen sharing finally sends audio too — the video track was forwarded to peers but the system-audio track from getDisplayMedia was captured and dropped, so viewers saw your share but heard nothing (the "others can\'t hear me while streaming" bug); the minimized call PiP video now switches to whoever is CURRENTLY SPEAKING (per-peer analysers ranked live, only peers with camera on can win, sticky so silence doesn\'t blank the video); mobile joiners appear as tiles now — the old code bound remoteStreams[0] to EVERY remote session so the third joiner\'s tile went blank (audible but invisible), now matched by userId through the peers map; the DJ Booth host gets a local volume slider matching the listener knob; and the Spidr AI voice-call menu drops OS emojis for custom Spidr iconography in accent colors, matching the AI\'s look everywhere else. Homepage: recent DMs and group chats now live in a persistent right rail on wider screens, one click to hop back in — and the mid-column duplicate is gone. Group Chat Settings: Save Changes now actually persists for non-owner members — the CRUD PATCH was owner-only and silently 403-ing on member edits despite the UI promising "any member can save name/avatar changes"; the group route now allows any member to update name/avatar/banner (owner still controls everything else) plus a proper error toast so future failures surface loudly instead of vanishing.' },
  { id: 'p1934', title: 'Patch 1.9.34 — Tactical context menus everywhere', date: '2026-07-08', type: 'UPDATE', description: 'The server member right-click menu has been rebuilt from scratch — the emoji-and-clashing-colors popup is dead. Right-clicking a member now opens the same frosted-glass tactical palette used across Spidr, upgraded for the job: an identity header with their avatar and live in-voice status, sharp vector icons on every row, and a strict tone hierarchy — neutral actions glow white, reversible moderation (kick, voice disconnect) glows orange, and destructive actions (permanent ban) glow Spidr red only when you hover them. Voice moderation folds in cleanly: server mute and deafen flip their labels to match the member\'s current state, and Move to Channel expands inline with the actual channel list. Profile and Direct Message sit at the top as first-class actions. THE WEB gets fuller right-click powers on every strand: Save to Collection opens your picker, Relay to Your Web toggles (and reads Un-Relay when already relayed), View Their Web jumps into the creator\'s profile, and your own posts gain a red Delete. Unpinning is everywhere it should be: friend and group right-click menus read Unpin from Spidr Web when something is pinned, and right-clicking a pinned head in the Spidr Web row unpins it instantly.' },
  { id: 'p1933', title: 'Patch 1.9.33 — Hotfix: Friends page crash + call join error', date: '2026-07-08', type: 'FIX', description: 'Two runtime crashes squashed. The Friends page went blank with \'pinned is not defined\' — the pinned-groups row referenced a variable that only existed in a different component scope; since that row only ever renders pinned groups, the pin badge now renders unconditionally there. And joining any voice call threw \'getMediaPrefs is not defined\' — the device-preferences import never landed in the WebRTC engine, so your chosen mic and camera settings crashed the join instead of applying. Both fixed, plus a codebase-wide sweep for the same class of bug (identifiers used without their import — the one failure our bundler cannot catch) came back clean.' },
  { id: 'p1932', title: 'Patch 1.9.32 — Speaking rings resurrected + TURN relay', date: '2026-07-08', type: 'FIX', description: 'Root-caused the dead speaking animations: every voice tile spun up its own Web Audio context, the minimized pill added another, and each mute or deafen toggle tore them down and rebuilt them — Chrome allows about six audio contexts per page, the pool exhausted mid-call, and every speaking ring in the app silently died. All analysers now share ONE app-wide audio context that never closes, and the pill\'s broadcaster reads mute state through a ref so toggling never churns audio plumbing. Rings pulse again — tiles, expanded deck, and the minimized pill. Second fix: cross-network calling. The client has always requested ICE relay config from /voice/ice, but that endpoint did not exist — every call silently fell back to STUN-only, which cannot punch through strict NATs, producing the classic \'call connects on the same wifi but never between homes\' failure. The endpoint now exists and serves your TURN relay credentials from server env (Metered free tier or any provider; see .env.example) alongside STUN. Set TURN_URLS, TURN_USERNAME, and TURN_CREDENTIAL on the server and cross-network + Electron↔web calls have a guaranteed path.' },
  { id: 'p1931', title: 'Patch 1.9.31 — One Spidr Web, not two', date: '2026-07-08', type: 'FIX', description: 'The Friends page briefly showed two pinned rows — a duplicate "Pinned to your web" strip stacked on top of the real SPIDR WEB row. The duplicate is gone. Pins now live INSIDE the Spidr Web row itself: pinned conversations render first with a red pin badge (keeping their live unread counts and presence dots), recents follow, and nothing appears twice. Right-click any head to pin or unpin it on the spot — same for the pin action in friend and group right-click menus, which feeds the same single store, synced to your profile so pins follow you across devices.' },
  { id: 'p1930', title: 'Patch 1.9.30 — Real device detection + full-app audit', date: '2026-07-07', type: 'UPDATE', description: 'Voice & Video settings now detect your ACTUAL hardware: every microphone, speaker, and camera on your system enumerates by name (with a one-tap permission grant, since browsers hide device labels until mic access is allowed once), hot-plug refreshes the lists live, and your picks persist and apply to real calls — mic and camera constraints in WebRTC capture, speakers via setSinkId on every incoming voice stream. Plus a live mic meter and camera preview so you can verify a device before joining. The homepage gets a JUMP BACK IN section: your recent DM conversations and group chats, one tap to land inside. Outgoing friend requests are now cancellable from the Sent list — cancelling removes both sides of the pair so no ghost request lingers. And a full-codebase audit (every one of ~390 files parse-checked, every client write diffed against server schemas, every dispatched event traced to a listener, every API path matched to a route) surfaced and fixed six silent data-loss bugs: SERVER BANS never persisted (banned users could just rejoin), server-invite DMs lost their invite card on reload, event creator attribution, moderator report resolutions, voice speaking sync, and imported-bot metadata were all being dropped by schema strict mode. Right-click Reply on a comment now actually opens the reply box, and a malformed dead file that could have broken future builds was removed.' },
  { id: 'p1929', title: 'Patch 1.9.29 — Voice polish + Apple Music module', date: '2026-07-07', type: 'UPDATE', description: 'The minimized call pill finally reacts to your voice — its tick-ring pulses live with your mic amplitude (the animation was always built in; nothing ever fed it a signal). Deafen now truly deafens: it silences every incoming voice INCLUDING people who join after you toggled it — late joiners used to slip through unmuted. Group chats get identity: set a group pfp AND a wide banner, static images or animated GIFs (GIFs skip the cropper so the animation survives), and both render in the chat header — plus a schema fix means pfp changes actually persist now instead of silently vanishing. The desktop app gets the big one: Electron denies mic/camera/screen permission requests by default when no handler is registered — a permission handler now grants the media family, and the macOS build gains the entitlements + usage descriptions Apple requires, which unblocks calling and streaming in the packaged exe/app. And Apple Music joins Module Nexus: an installable Now Playing widget with connect-in-place, live track when you\'re playing through Spidr, and an honest LAST PLAYED fallback (Apple has no live API) — visitors see the profile owner\'s spins, never their own.' },
  { id: 'p1928', title: 'Patch 1.9.28 — QA polish sweep', date: '2026-07-07', type: 'FIX', description: 'Unread DM badges now clear the moment you open a conversation — the mark-read call was landing server-side but the friends-list badge cache was never told to refresh, so the count haunted you until a reload. Spidr AI drops the OS emojis: every message from the AI now renders custom Spidr-system iconography inline (the spider gets its own bespoke sigil), in channels, DMs, and the AI panel. Verified functional this pass: tapping any post tile on a WEB profile (yours or anyone\'s) jumps the feed straight to that strand; usernames and avatars in feed comments open that user\'s full WEB profile; ENTER USER WEB routes from any profile card in the app onto THE WEB with their node open; Pin to Web from the friends page persists to your profile and surfaces in the DM sidebar; status changes ask how long (30m / 1h / 4h / 8h / until changed) and auto-revert on expiry; the Biomass shop stocks exactly custom titles, chat colors, and chat fonts — buy, equip, and they render on your nameplate and messages; the bookmark on any strand opens a collection picker (choose, toggle, or create-new); and servers carry #tags editable in Server Settings that Signal Radar filters on.' },
  { id: 'p1927', title: 'Patch 1.9.27 — Apple Music arrives', date: '2026-07-06', type: 'UPDATE', description: 'Spidr now speaks Apple Music — something Discord flat-out does not have. Connect your account from Neural Config (Apple\'s own authorization popup, your credentials never touch our servers). The DJ Booth gets an APPLE MUSIC tab next to Spotify: Apple still ships 30-second previews for virtually its entire catalog, so every listener hears the booth — and if you\'re a connected Apple Music subscriber, the booth upgrades you to the FULL track, synced to the session clock, with a Full Track badge so you know you\'re getting the real thing. Playing through Spidr broadcasts your now-playing to friends in real time via the same presence pipeline as Spotify and the desktop OS reader. Honest print: Apple has no live now-playing API, so presence comes from playback through Spidr or the desktop Music app — and full-track mode requires an active Apple Music subscription; previews cover everyone else.' },
  { id: 'p1926', title: 'Patch 1.9.26 — THE WEB grows up + desktop release prep', date: '2026-07-05', type: 'UPDATE', description: 'THE WEB sheds its last borrowed feather: the personalized feed label is now YOUR WEB (no more TikTok-style wording), and tapping any creator\'s name or avatar in the feed opens THEIR full WEB profile — strands and relays included — right inside the feed. Sling to DM is real now, with its own lane: slung posts land in the new SIGNALS tab instead of your actual DMs, so sharing clips never floods real conversations. The DJ Booth finally makes sound — when the host picks a track, everyone in the channel hears the 30-second preview looped in rough sync, with local volume control (tracks Spotify ships no preview for say so honestly instead of playing silence). Spidr AI is audible to the whole call, not just whoever summoned it. The DJ stage swaps its grid-lines backdrop for a deep red/purple gradient. Nameplates get the Sonic Uplink (glowing 4-bar equalizer when someone\'s broadcasting music) and the Activity Blade (a razor-thin frosted tag showing what they\'re playing) — rich presence the Spidr way, no bulky Discord rectangles. Notification & sound toggles in Settings actually save and apply now. And the desktop app gears up for release: a woven-web boot splash, a fully transparent title bar that lets your background bleed through, collapsible server and channel sidebars, and the Spidr mascot as the real .exe / .app icon.' },
  { id: 'p1925', title: 'Patch 1.9.25 — Spidr Apex + platform hardening', date: '2026-07-05', type: 'UPDATE', description: 'Spidr Apex ($7.99/mo, $69.99/yr) subscription flow is live end-to-end — signed Stripe webhook writes apex_tier, checkout + billing portal routes, 30-day trial gated by a burn-once flag on the profile so cancel-and-resubscribe pays from day one, and idempotent webhook processing means Stripe redeliveries can\'t double-flip anyone. Platform-wide security pass: every user-owned CRUD collection (AI logs, DMs, group chats, friends, collections, saved audio, custom bots, community assets, servers, events, feeds, reports) now locks PATCH/DELETE to the owner — no more cross-account writes. Server audit logs are now truly append-only via HTTP. Legacy Node.js auth endpoints return 410 for anything except TOTP, so the Spring Boot MFA gate can\'t be bypassed. Node dependency vulns cleared (nodemailer + uuid majors bumped).' },
  { id: 'p1924', title: 'Patch 1.9.24 — Streak Counter + Steam Now Playing modules unlocked', date: '2026-07-02', type: 'UPDATE', description: 'Two modules step out of Coming Soon. The Daily Streak Counter is now real — instead of guessing your streak from message activity, the server tracks a proper day-by-day login streak on your profile: a /streak/ping endpoint fires once per session on login so consecutive days count up, missing a day resets the current streak to zero, and best and total-days climb alongside it. The streak fields are locked at the CRUD layer so nobody can PATCH themselves a higher number. Steam Now Playing is unlocked in the Module Nexus and installs like any other module — enter your 64-bit Steam ID, pick a game from your library, and the widget renders the game\'s header art, total hours, past-two-weeks hours, and achievement progress against Steam\'s public API. The widget UI and the server\'s /steam/games and /steam/stats routes were already in the tree; they were just gated by the padlock overlay in ModuleCard until now.' },
  { id: 'p1923', title: 'Patch 1.9.23 — Bot Lab tidy + Spidr Protocol fixes', date: '2026-06-30', type: 'FIX', description: 'Two cleanup passes. The Bot Laboratory drops the Data Analyst bot and swaps its category-grouped layout for a single alphabetical list — one clean A→Z grid of official bots instead of Scientists / Guardians / Utility sections. And the Spidr Protocol ghost overlay finally sends messages properly and drags where you want it: sends now route to the correct backend for DMs, group chats, and server channels (group chats were silently hitting the wrong endpoint before), and grabbing the top drag rail no longer flips interactive mode off mid-drag so the overlay pins wherever you put it. A colored status pill next to the input surfaces send success or failure inline.' },
  { id: 'p1922', title: 'Patch 1.9.22 — Tablet chat headers + server avatars', date: '2026-06-30', type: 'FIX', description: 'A polish pass for chat headers and avatars. The DM and group chat headers no longer crowd themselves on tablets — they collapse into the same compact hamburger menu that mobile already uses, so the floating top-right action cluster stops fighting for space. Sticky Web has been renamed Memory Web in the quick-actions dropdown. And server channel messages now show live profile avatars the same way DMs and group chats already do — when someone changes their picture, it updates everywhere their messages appear, not just in DMs.' },
  { id: 'p1921', title: 'Patch 1.9.21 — Spotify module privacy fix', date: '2026-06-29', type: 'FIX', description: 'Spotify module privacy fix. The Spotify Now Playing module used to show YOUR track on every profile — now each profile shows its owner\'s track, just like the Weather widget. Visitors see what the profile owner is listening to (if they\'ve connected Spotify), and the "Connect Spotify" and "Disconnect" controls only appear on your own profile.' },
  { id: 'p192', title: 'Patch 1.9.2 — Bot Lab cleanup + mobile polish', date: '2026-06-28', type: 'UPDATE', description: 'A focused cleanup release. Music Master and Game Master have been retired — the Bot Laboratory now only ships the official guardian and scientist bots that are fully working. The "My Bots" / Fabricator tab is hidden until user-created bots are ready. Mobile polish lands across DMs, Friends, Servers, the Bot Lab, and the home dashboard — headers collapse cleanly on small screens, the DM action rail tucks into a dropdown menu, and the Friends tab strip scrolls horizontally instead of wrapping. Flickery UI signals (typing banners, web vibration alerts) are now smoothed so they don\'t flash on brief gaps. And SPIDR_SYS itself got a plain-language rewrite — every patch note now reads like product news, not a code review.' },
  { id: 'p191', title: 'Patch 1.9.1 — Home + chat polish', date: '2026-06-27', type: 'FIX', description: 'A polish pass for the home page and chats. Activity Feed and Recent Servers on the home page now collapse with a chevron, and your choice is remembered. Biomass catches no longer spam the chat you\'re in — they\'re logged into the Spidr System DM with their toast instead. And message avatars across DMs and group chats now update everywhere when someone changes their profile picture.' },
  { id: 'p19m', title: 'Patch 1.9 — Spidr Mobile (Phase 1) is now live', date: '2026-06-20', type: 'UPDATE', description: 'Spidr is officially on iPhone and Android. Your friends, DMs, servers, and clips all come with you — log in once, everything stays in sync with the web app. THE WEB feed swipes vertically like TikTok, comments slide up from the bottom, and likes and follows count toward your personalized feed across web and mobile. Voice channels and the upload studio are coming in Phase 2.' },
  { id: 'p185', title: 'Patch 1.8.5 is now live', date: '2026-06-16', type: 'UPDATE', description: 'Three changes this patch. Friend avatars are now live everywhere — when a friend changes their profile picture, you see it instantly across the Friends panel, Spidr Web, and pending requests. Spotify presence is faster and lighter on traffic. And there\'s a brand-new 404 page — a hand-drawn cave-and-web scene with the Spidr mascot lost in the middle of the web.' },
  { id: 'p184', title: 'Patch 1.8.4 is now live', date: '2026-06-16', type: 'UPDATE', description: 'DJ Booth is live in voice channels. Pick the green Music icon in the call dock, search Spotify, and the whole room sees synchronized DJ visuals — spinning album art, pulse rings, and a bouncing audience. Note: this is the visual layer — each listener still plays the host\'s track on their own Spotify. Plus: Spotify search actually returns results now, expanding a minimized call routes you home properly, and the Mutuals tab is hidden on your own profile.' },
  { id: 'p183', title: 'Patch 1.8.3 is now live', date: '2026-06-15', type: 'FIX', description: 'Weather widget privacy fix. The Weather widget used to show YOUR weather on every profile — now each user has their own saved location, and viewing a profile shows THEIR weather. The city and region name have also been removed from the display, so the owner\'s exact location stays private.' },
  { id: 'p182', title: 'Patch 1.8.2 is now live', date: '2026-06-15', type: 'UPDATE', description: 'A big features patch. Voice channels get Theater Mode when someone shares their screen, and minimized calls now show a live preview of what\'s happening. Repost lands on THE WEB — share any clip to your feed. Profile Anthem lets you set a song that auto-plays (muted) when someone views your profile. Plus: a nameplate cropper, shareable server invite cards, clickable links in chat, a Join by Invite Code tab on the Create Server dialog, comment replies in the notification center, and Spotify Now Playing in your browser (closed beta — ping Chris for access).' },
  { id: 'p181', title: 'Patch 1.8.1 is now live', date: '2026-06-12', type: 'FIX', description: 'Welcome Bot now greets every new member, not just the ones who joined via invite link. Browse-and-Join users get the greeting too.' },
  { id: 'p18web', title: 'Patch 1.8 — The Web Fixes', date: '2026-06-12', type: 'FIX', description: 'Slash commands got a serious upgrade. The autocomplete popup is now grouped by bot with avatars and colors, hides admin-only commands from non-admins, and shows up to 30 results with arrow-key navigation. New Auto Moderator commands: /modhelp, /modreset, /modtest, /modset unban all. New Welcome Bot commands: /welcomehelp, /welcomeconfig, /welcomedelete. Admins can now delete bot and system messages in their server. Plus a fix for the Copy Channel ID toast that flashed before the copy actually finished.' },
  { id: 'p18', title: 'Patch 1.8 is now live', date: '2026-06-10', type: 'UPDATE', description: 'All four official bots are now fully working. Auto Moderator scans every message for spam and banned words — configure thresholds and word lists in the Bot Laboratory. Welcome Bot greets new members in your server\'s first text channel with a template you control. Game Master runs trivia: /trivia posts a question with four options, first correct answer wins. Music Master\'s /play now shows the actual song title, and /skip and /stop clear cleanly.' },
  { id: 'p172', title: 'Patch 1.7.2 is now live', date: '2026-06-09', type: 'FIX', description: 'A polish pass on THE WEB. "Cocoons" is now called "Saved" everywhere — feed, profile tabs, and collections. The volume slider no longer disappears when you reach for it. GIF and image panels in comments close automatically when you scroll to a new video. And clicking a saved clip jumps you straight to it in the feed.' },
  { id: 'p171', title: 'Patch 1.7.1 is now live', date: '2026-06-08', type: 'FIX', description: 'Adding a friend you\'ve already added now shows "You already added this user!" instead of a confusing error. And SPIDR_SYS got caught up — patches 1.6.2, 1.7, and the deploy fix are all in the feed now.' },
  { id: 'p17', title: 'Patch 1.7 is now live', date: '2026-06-03', type: 'UPDATE', description: 'Module Nexus got a big overhaul. Gaming Uplink now detects games from every launcher — League of Legends, VALORANT, TFT, Steam, Epic, Battle.net, Game Pass, and more — with auto-extracted icons. Background apps (Medal, Discord, Spotify, OBS) no longer get mistaken for games. Spotify Now Playing is live in the desktop app: connect Spotify in Settings and your current track shows on your profile. New "Don\'t see your game?" form lets you flag missing detection. Plus desktop app polish: Spidr icon, drag the window from the top, resize, and the APEX upgrade dialog actually shows up now.' },
  { id: 'p162', title: 'Patch 1.6.2 is now live', date: '2026-06-02', type: 'UPDATE', description: 'A behind-the-scenes rebuild of the app\'s shell — same look, but the mobile menu is cleaner and pages load faster. A few legacy pages were retired to make room for the newer home dashboard and integrated profile flows.' },
  { id: 'p162b', title: 'Deploy pipeline fixed', date: '2026-06-02', type: 'FIX', description: 'Fixed the production deploy pipeline — releases to the web app no longer time out, so updates land reliably again.' },
  { id: 'p161', title: 'Patch 1.6.1 is now live', date: '2026-05-31', type: 'FIX', description: 'A polish pass on Patch 1.6. Voice channels now drop a vertical "web thread" to glowing crimson avatar nodes. The expanded call deck got a cleaner glass look, and screen share splits into a proper Main Stage with a collapsible sidebar of audio-reactive user pills. Minimized calls became a tiny "Micro-Tactical HUD" pill that fades when idle. New: a transparent "Spidr Protocol" overlay (desktop) lets you chat over a game without leaving it. Fixes: group chats no longer render blank, voice calls no longer show duplicate users, the message feed is cleaner, and the profile widget stopped overlapping content.' },
  { id: 'p16', title: 'Patch 1.6 is now live', date: '2026-05-31', type: 'UPDATE', description: 'The biggest visual and functionality pass yet. THE WEB feed: trending posts physically pulse, The Weaver upload studio gets signature filters, a precision dual-handle video scrubber, and external audio from YouTube / Spotify / Apple Music. New: tap-to-expand image lightbox in chat, rich GIF and image comments, and long-press menus on mobile. The channel sidebar, server chat, and Bot Laboratory all got reskinned in the crimson palette. Custom backgrounds now flow across the whole app. Plus a bunch of fixes: minimized calls work reliably, server permissions are correct, mute and deafen are properly distinct, "Pin to Web" confirms, tapping a Memory Web message jumps to it, voice channels show their members, and mobile is fully responsive.' },
  { id: 'p15', title: 'Patch 1.5 is now live', date: '2026-05-29', type: 'UPDATE', description: 'APEX Symbiote suite lands: Profile Takeover overlay, Stream HUD with live telemetry, Frame Vault, Nexus Grid sidebar, and custom Nameplates & Badges. Plus fixes: minimized calls use the new Web Node design everywhere, minimizing no longer disconnects you, the sidebar logo box is gone, APEX activation is fixed, and trending servers no longer 404.' },
  { id: 'p14', title: 'Patch 1.4 is now live', date: '2026-05-24', type: 'UPDATE', description: 'APEX gets hanging threads and mini voice visualizers. Calls auto-minimize when you navigate, the desktop app supports picture-in-picture, and you can now "Pin to Spidr Web" across Friends, DMs, and Groups.' },
  { id: 'voicefix', title: 'Voice messages fixed everywhere', date: '2026-05-24', type: 'FIX', description: 'Voice messages now send everywhere — DMs, group chats, and server channels. Fixed the upload error that was blocking them.' },
  { id: 'webnode', title: 'Suspended Web Node', date: '2026-05-23', type: 'UPDATE', description: 'Minimized calls now appear as a draggable "web node" — a glowing radial pill with an active-speaker waveform and your APEX-colored thread.' },
  { id: 'unicall', title: 'Universal calling', date: '2026-05-23', type: 'UPDATE', description: 'DM and group calls now use the exact same voice deck and screen share as server channels — one unified call experience.' },
  { id: 'trending', title: 'Trending server join flow', date: '2026-05-22', type: 'FIX', description: 'Opening a server from Trending no longer 404s. Non-members now see a proper Join / Request Invite screen.' },
];

const API_BASE = (import.meta.env.VITE_API_URL) || 'http://localhost:4000';
const TYPE_COLORS = {
  UPDATE: 'text-[#FF3333] border-[#FF3333]/40',
  ALERT:  'text-amber-400 border-amber-400/40',
  FIX:    'text-emerald-400 border-emerald-400/40',
};

export default function SpidrSystem() {
  const isMobile = useIsMobile();
  const [open, setOpen] = useState(false);
  // On <md, the X button fully dismisses the terminal (ticker disappears too)
  // instead of just collapsing it. Re-opening is then only possible via the
  // sidebar's "Spidr System" row (which fires `spidr-system-open`). On desktop
  // we keep the original collapse-to-ticker behavior since desktop has no
  // sidebar trigger to bring it back from a full dismiss.
  const [dismissed, setDismissed] = useState(false);
  const [news, setNews] = useState(MOCK_NEWS);
  const [hasUnread, setHasUnread] = useState(false);
  const [typed, setTyped] = useState('');
  const typeTimer = useRef(null);

  // Fetch live news (best-effort; falls back to mock).
  useEffect(() => {
    let alive = true;
    fetch(`${API_BASE}/system/news`)
      .then(r => r.ok ? r.json() : null)
      .then(data => { if (alive && Array.isArray(data) && data.length) setNews(data); })
      .catch(() => { /* keep mock */ });
    return () => { alive = false; };
  }, []);

  // Unread = newest id differs from the last one the user saw.
  useEffect(() => {
    const newestId = news[0]?.id;
    if (!newestId) return;
    let seen = null;
    try { seen = localStorage.getItem('spidr_system_seen'); } catch {}
    setHasUnread(seen !== newestId);
  }, [news]);

  // External open trigger — any component can fire `spidr-system-open` to
  // pop the terminal open (e.g. the MobileMenuPanel row). Also un-dismisses
  // so the sidebar can resurrect the terminal after the user X'd it on mobile.
  useEffect(() => {
    const handler = () => { setDismissed(false); setOpen(true); };
    window.addEventListener('spidr-system-open', handler);
    return () => window.removeEventListener('spidr-system-open', handler);
  }, []);

  // Typewriter the newest note's description when the terminal opens.
  useEffect(() => {
    clearInterval(typeTimer.current);
    if (!open) { setTyped(''); return; }
    const full = news[0]?.description || '';
    let i = 0;
    typeTimer.current = setInterval(() => {
      i += 2;
      setTyped(full.slice(0, i));
      if (i >= full.length) clearInterval(typeTimer.current);
    }, 16);
    // Mark newest as seen.
    try { if (news[0]?.id) localStorage.setItem('spidr_system_seen', news[0].id); } catch {}
    setHasUnread(false);
    return () => clearInterval(typeTimer.current);
  }, [open, news]);

  const latest = news[0];

  // On mobile, the user has explicitly told the terminal to go away — render
  // nothing until the sidebar resurrects it via `spidr-system-open`.
  if (dismissed && isMobile) return null;

  return (
    <div className="fixed bottom-20 md:bottom-4 right-4 z-50">
      <AnimatePresence mode="wait">
        {open ? (
          <motion.div
            key="expanded"
            initial={{ opacity: 0, y: 30, height: 0 }}
            animate={{ opacity: 1, y: 0, height: 384 }}
            exit={{ opacity: 0, y: 30, height: 0 }}
            transition={{ type: 'spring', stiffness: 320, damping: 30 }}
            className="w-80 bg-[#050505]/90 backdrop-blur-md border border-red-900/30 rounded-lg overflow-hidden flex flex-col shadow-2xl shadow-black/60"
          >
            {/* Header */}
            <div className="flex items-center justify-between px-3 py-2 border-b border-red-900/30">
              <span className="flex items-center gap-2 font-mono text-xs text-[#FF3333]">
                <Terminal size={13} /> SPIDR_SYS
              </span>
              <button
                onClick={() => { if (isMobile) setDismissed(true); else setOpen(false); }}
                className="text-zinc-500 hover:text-white transition-colors"
              >
                <X size={14} />
              </button>
            </div>

            {/* Scrollable list */}
            <div className="flex-1 overflow-y-auto p-3 space-y-3 font-mono text-xs">
              {news.map((item, idx) => (
                <div key={item.id} className={idx > 0 ? 'pt-3 border-t border-red-900/20' : ''}>
                  <div className="flex items-center gap-2 mb-1">
                    <span className={`px-1.5 py-0.5 rounded border text-[9px] font-bold ${TYPE_COLORS[item.type] || TYPE_COLORS.UPDATE}`}>
                      {item.type}
                    </span>
                    <span className="text-zinc-600 text-[10px]">{item.date}</span>
                  </div>
                  <p className="text-zinc-200 font-bold text-[11px]">{item.title}</p>
                  <p className="text-zinc-400 mt-0.5 leading-relaxed">
                    {idx === 0 ? typed : item.description}
                    {idx === 0 && typed.length < (item.description?.length || 0) && (
                      <span className="inline-block w-1.5 h-3 bg-[#FF3333] ml-0.5 animate-pulse align-middle" />
                    )}
                  </p>
                </div>
              ))}
            </div>
          </motion.div>
        ) : (
          <motion.button
            key="collapsed"
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0 }}
            onClick={() => setOpen(true)}
            className="relative bg-[#050505]/80 backdrop-blur-md border border-red-900/30 rounded-md px-4 py-2 flex items-center gap-2 max-w-[320px] hover:border-red-900/50 transition-colors"
          >
            <span className="font-mono text-xs text-[#FF3333] shrink-0">{'>'} SPIDR_SYS:</span>
            <span className="font-mono text-xs text-zinc-300 truncate">{latest?.title || 'All systems nominal.'}</span>

            {/* Spider-Sense unread badge — glowing node + jagged line */}
            {hasUnread && (
              <span className="absolute -top-1.5 -right-1.5">
                <svg width="20" height="20" viewBox="0 0 20 20">
                  <path d="M4 14 L8 10 L6 8 L11 4" fill="none" stroke="#FF3333" strokeWidth="1.2" opacity="0.8" />
                  <circle cx="14" cy="6" r="4" fill="#FF3333">
                    <animate attributeName="opacity" values="1;0.4;1" dur="1.2s" repeatCount="indefinite" />
                  </circle>
                  <circle cx="14" cy="6" r="6" fill="none" stroke="#FF3333" strokeWidth="1" opacity="0.4" />
                </svg>
              </span>
            )}
          </motion.button>
        )}
      </AnimatePresence>
    </div>
  );
}
