import { base44 } from '@/api/base44Client';

// The Spidr AI bot command processor
// Returns { response, actions?, streamUrl?, streamType? } or null if not a command

const ROASTS = [
  "Scanning profile... Error 404: Personality not found. Try upgrading your firmware.",
  "Your profile picture looks like it was generated by an AI that gave up halfway.",
  "I've seen better chat game from a captcha.",
  "You type slower than I think, and I have to pretend to think.",
  "Your server contributions are like dark matter — theoretically there, but nobody can prove it.",
  "I'd roast you harder but I'm worried you'd take it as a compliment.",
];

const EIGHT_BALL = [
  "The web says yes.",
  "My silk threads say no.",
  "Absolutely. I'd stake 8 legs on it.",
  "Not a chance. Even my webs aren't that sticky.",
  "Ask again when Mercury isn't in retrograde.",
  "Signs point to maybe. I'm a spider, not a fortune teller.",
  "The vibrations in my web suggest... yes.",
  "I wouldn't bet my exoskeleton on it.",
  "100%. The spider sense is tingling.",
  "Outlook unclear. Too many flies buzzing around.",
];

const FACTS = [
  "Spiders can survive in space for short periods.",
  "The world's largest spider web was found in Madagascar, spanning 82 feet.",
  "Some spiders can walk on water.",
  "Jumping spiders can see colors humans can't.",
  "Spider silk is stronger than steel by weight.",
  "There's a spider that builds a decoy of itself in its web.",
  "Spiders have been on Earth for over 380 million years.",
];

export async function processBotCommand(text, currentUser, serverId, channelId) {
  if (!text.startsWith('/')) return null;
  
  const parts = text.slice(1).split(/\s+/);
  const cmd = parts[0]?.toLowerCase();
  const args = parts.slice(1).join(' ');

  switch (cmd) {
    case 'play':
    case 'stream':
    case 'watch': {
      if (!args) {
        return {
          response: "Usage: /play <YouTube or Twitch URL>\n\nExample:\n/play https://youtube.com/watch?v=dQw4w9WgXcQ\n/play https://twitch.tv/shroud",
        };
      }
      
      let streamType = 'video';
      if (args.includes('twitch.tv')) streamType = 'twitch';
      else if (args.includes('youtube.com') || args.includes('youtu.be')) streamType = 'youtube';
      else if (args.includes('music') || args.includes('spotify')) streamType = 'music';

      return {
        response: `Initializing Neural Sync Protocol...\nTargeting stream: ${args}\nAll connected users will see the stream. Enjoy!`,
        streamUrl: args,
        streamType,
      };
    }

    case 'roast': {
      const target = args || currentUser?.full_name || 'you';
      const roast = ROASTS[Math.floor(Math.random() * ROASTS.length)];
      return {
        response: `🎯 Target acquired: ${target}\n\n${roast}`,
      };
    }

    case '8ball': {
      const answer = EIGHT_BALL[Math.floor(Math.random() * EIGHT_BALL.length)];
      return {
        response: `🎱 Question: "${args || 'Will I be lucky?'}"\n\n${answer}`,
      };
    }

    case 'roll': {
      const max = parseInt(args) || 6;
      const result = Math.floor(Math.random() * max) + 1;
      const diceEmojis = ['⚀', '⚁', '⚂', '⚃', '⚄', '⚅'];
      const emoji = max === 6 ? (diceEmojis[result - 1] || '🎲') : '🎲';
      return {
        response: `${emoji} Rolling a d${max}...\n\n>>> ${result} <<<`,
      };
    }

    case 'hack': {
      const target = args || 'the mainframe';
      return {
        response: `🕷️ INITIATING HACK SEQUENCE ON: ${target}\n\n[████████░░░░] 67% — Bypassing firewall...\n[██████████░░] 83% — Extracting data...\n[████████████] 100% — COMPLETE\n\nResults: Found 847 cat photos and a half-finished novel. Target is embarrassingly human.`,
      };
    }

    case 'vibe': {
      const vibes = ['🌊 Ocean chill', '🔥 Fire mode', '🌙 Night owl', '⚡ Hyperdrive', '🕷️ Web crawler', '🎮 Gamer rage'];
      const vibe = vibes[Math.floor(Math.random() * vibes.length)];
      return {
        response: `Current vibe check: ${vibe}\n\nVibes are immaculate. No further analysis needed.`,
      };
    }

    case 'fact': {
      const fact = FACTS[Math.floor(Math.random() * FACTS.length)];
      return {
        response: `🕷️ Spider Fact:\n\n${fact}`,
      };
    }

    case 'ask': {
      if (!args) {
        return { response: "Usage: /ask <your question>\n\nI'll use my neural web to find an answer." };
      }
      // Use LLM for custom questions
      const llmResult = await base44.integrations.Core.InvokeLLM({
        prompt: `You are Spidr AI, a witty, edgy AI bot inside a social platform called Spidr. You speak in a cool, slightly glitchy, tech-noir style. Keep responses under 200 characters. Be helpful but with personality. The user asks: "${args}"`,
        response_json_schema: {
          type: 'object',
          properties: {
            answer: { type: 'string' }
          }
        }
      });
      return {
        response: llmResult.answer || "My neural web is tangled. Try again.",
      };
    }

    case 'help': {
      return {
        response: `🕷️ SPIDR_AI COMMAND PROTOCOL\n\n` +
          `/play <url> — Stream YouTube/Twitch in voice\n` +
          `/roast <name> — Get roasted by AI\n` +
          `/8ball <question> — Magic 8-ball\n` +
          `/roll <sides> — Roll dice (default: 6)\n` +
          `/hack <target> — Fake hack sequence\n` +
          `/vibe — Vibe check\n` +
          `/fact — Random spider fact\n` +
          `/ask <question> — Ask Spidr AI anything\n` +
          `/help — Show this list`,
      };
    }

    default:
      return null;
  }
}