const test = require('node:test');
const assert = require('node:assert/strict');
const { randomUUID } = require('node:crypto');

// Opt-in integration suite. Only a new, uniquely named LOCAL database is used.
test('message persistence, access controls, read receipts and call signaling', { skip: process.env.SPIDR_LOCAL_INTEGRATION !== '1', timeout: 30000 }, async t => {
  const mongoose = require('mongoose');
  const express = require('express');
  const http = require('node:http');
  const jwt = require('jsonwebtoken');
  const { Server: SocketServer } = require('socket.io');
  const { io: client } = require('../../spidr-client/node_modules/socket.io-client');
  const dbName = 'spidr_qa_' + randomUUID().replaceAll('-', '');
  await mongoose.connect('mongodb://127.0.0.1:27017/' + dbName, { serverSelectionTimeoutMS: 3000 });
  t.mock.method(require('../src/utils/notifications'), 'dispatch', async () => ({ sent: false }));
  t.mock.method(require('../src/utils/push'), 'sendCallEndPush', async () => {});
  t.mock.method(require('../src/utils/spidrSystem'), 'ensureSystemFriendship', async () => {});
  const User = require('../src/models/User');
  const DM = require('../src/models/DirectMessage');
  const Saved = require('../src/models/SavedMessage');
  const Server = require('../src/models/Server');
  const Message = require('../src/models/Message');
  const Group = require('../src/models/GroupChat');
  const GroupMessage = require('../src/models/GroupChatMessage');
  const Voice = require('../src/models/VoiceSession');
  const Friend = require('../src/models/Friend');
  await Saved.init();
  const users = await User.insertMany(['Alice', 'Bob', 'Eve'].map(name => ({ email: name + '@example.test', password: 'test-only', full_name: name, username: name })));
  const [alice, bob, eve] = users.map(u => String(u._id));
  const token = id => jwt.sign({ userId: id }, require('../src/utils/jwtSecret').getSecret(), { expiresIn: '5m' });
  const app = express();
  app.use(express.json());
  app.use('/message-actions', require('../src/routes/messageActions'));
  const httpServer = http.createServer(app);
  const io = new SocketServer(httpServer);
  app.set('io', io);
  require('../src/socket/handlers')(io);
  await new Promise(resolve => httpServer.listen(0, '127.0.0.1', resolve));
  const base = 'http://127.0.0.1:' + httpServer.address().port;
  const sockets = [];
  const connect = async id => {
    const socket = client(base, { auth: { token: token(id) }, transports: ['websocket'], forceNew: true, reconnection: false });
    sockets.push(socket);
    await new Promise((resolve, reject) => { socket.once('connect', resolve); socket.once('connect_error', reject); });
    return socket;
  };
  const action = (socket, event, data = {}) => new Promise((resolve, reject) => socket.timeout(3000).emit(event, data, (error, result) => error ? reject(error) : resolve(result)));
  const event = (socket, name) => new Promise((resolve, reject) => {
    const timer = setTimeout(() => reject(new Error('Missing event: ' + name)), 3000);
    socket.once(name, data => { clearTimeout(timer); resolve(data); });
  });
  const request = async (method, path, body, id = alice) => {
    const res = await fetch(base + '/message-actions' + path, { method, headers: { authorization: 'Bearer ' + token(id), 'content-type': 'application/json' }, ...(body ? { body: JSON.stringify(body) } : {}) });
    return { status: res.status, body: await res.json() };
  };
  t.after(async () => {
    sockets.forEach(socket => socket.disconnect());
    await new Promise(resolve => io.close(resolve));
    await new Promise(resolve => setTimeout(resolve, 100));
    assert.equal(mongoose.connection.name, dbName);
    assert.match(dbName, /^spidr_qa_[a-f0-9]{32}$/);
    await mongoose.connection.dropDatabase();
    await mongoose.disconnect();
  });
  const conversationId = [alice, bob].sort().join('-');
  const [message] = await DM.insertMany([{ sender_id: bob, receiver_id: alice, recipient_id: alice, conversation_id: conversationId, sender_name: 'Bob', content: 'Keep this message', attachments: [{ url: 'https://example.test/photo.png', type: 'image' }] }]);
  await Friend.insertMany([{ user_id: alice, friend_id: bob, status: 'accepted' }]);
  await t.test('bookmarks are durable, deduplicated and private', async () => {
    const body = { source_type: 'dm', message_id: String(message._id) };
    assert.equal((await request('POST', '/saved', body, eve)).status, 403);
    const results = await Promise.all([request('POST', '/saved', body), request('POST', '/saved', body)]);
    assert.ok(results.every(r => [200, 201].includes(r.status)));
    assert.equal(await Saved.countDocuments({ user_id: alice }), 1);
    const list = await request('GET', '/saved');
    assert.equal(list.body.items[0].content, message.content);
    assert.equal((await request('GET', '/saved', undefined, eve)).body.items.length, 0);
    assert.equal((await request('DELETE', '/saved/' + list.body.items[0].id, undefined, eve)).status, 404);
  });
  await t.test('forwarding preserves content/attachments and checks both conversations', async () => {
    const body = { source_type: 'dm', message_id: String(message._id), target_type: 'dm', target_id: bob };
    assert.equal((await request('POST', '/forward', body, eve)).status, 403);
    assert.equal((await request('POST', '/forward', { ...body, target_id: eve })).status, 403);
    const sent = await request('POST', '/forward', body);
    assert.equal(sent.status, 201);
    assert.equal(sent.body.sender_id, alice);
    assert.equal(sent.body.attachments[0].url, message.attachments[0].url);
    assert.match((await DM.findById(sent.body.id)).content, /^Forwarded from Bob:/);
  });
  await t.test('mark read is scoped to each server even when channel IDs repeat', async () => {
    const servers = await Server.insertMany(['One', 'Two'].map(name => ({ name, owner_id: alice, channels: [{ id: 'general' }] })));
    await Message.insertMany(servers.map(s => ({ server_id: String(s._id), channel_id: 'general', user_id: bob, content: 'Unread', created_date: new Date(Date.now() - 1000) })));
    const group = await Group.create({ name: 'Group', owner_id: alice, member_ids: [alice, bob] });
    await GroupMessage.insertMany([{ group_id: String(group._id), user_id: bob, content: 'Unread group' }]);
    assert.equal((await request('POST', '/read', { scope: 'server', context_id: String(servers[0]._id) }, eve)).status, 403);
    assert.equal((await request('POST', '/read', { scope: 'channel', server_id: String(servers[0]._id), context_id: 'general' })).status, 200);
    const state = (await request('GET', '/read-state')).body;
    assert.equal(state.channels[servers[0]._id].general, false);
    assert.equal(state.channels[servers[1]._id].general, true);
    await request('POST', '/read', { scope: 'group', context_id: String(group._id) });
    assert.equal((await request('GET', '/read-state')).body.groups[group._id], false);
    await request('POST', '/read', { scope: 'dm', context_id: bob });
    assert.equal((await DM.findById(message._id)).is_read, true);
  });
  await t.test('real sockets ring both devices and transfer to a new media owner', async () => {
    const pc = await connect(alice), phone = await connect(alice), receiver = await connect(bob), other = await connect(bob);
    const incoming = event(other, 'call:incoming');
    const invited = await action(pc, 'call:invite', { conversationId, recipientId: bob });
    assert.equal(invited.ok, true);
    assert.equal((await incoming).callId, invited.call.callId);
    assert.equal((await action(receiver, 'call:accept', { callId: invited.call.callId })).ok, true);
    const joined = event(receiver, 'voice:peer-joined');
    receiver.emit('voice:join', { serverId: 'dm', channelId: conversationId });
    await new Promise(resolve => setTimeout(resolve, 80));
    pc.emit('voice:join', { serverId: 'dm', channelId: conversationId });
    await joined;
    const ready = await action(phone, 'call:transfer:request', { callId: invited.call.callId });
    const moved = event(pc, 'call:transferred');
    assert.equal((await action(phone, 'call:transfer:commit', { callId: invited.call.callId, transferId: ready.call.transferId })).ok, true);
    await moved;
    const rejoined = event(receiver, 'voice:peer-joined');
    phone.emit('voice:join', { serverId: 'dm', channelId: conversationId });
    assert.equal((await rejoined).socketId, phone.id);
    const signal = event(receiver, 'voice:signal');
    phone.emit('voice:signal', { to: receiver.id, signal: { type: 'offer', sdp: 'test' } });
    assert.equal((await signal).userId, alice);
    pc.disconnect();
    await new Promise(resolve => setTimeout(resolve, 150));
    assert.equal(await Voice.countDocuments({ user_id: alice, channel_id: conversationId }), 1);
    assert.equal((await action(other, 'call:cancel', { callId: invited.call.callId })).ok, false);
    assert.equal((await action(receiver, 'call:cancel', { callId: invited.call.callId })).ok, true);
    assert.equal(await Voice.countDocuments({ channel_id: conversationId }), 0);
  });
  await t.test('missed call service writes a real database history row', async () => {
    const events = [];
    const fakeIO = { to: () => ({ emit: (name, payload) => events.push({ name, payload }) }) };
    const service = require('../src/socket/callSessionServices').createCallSessionServices(fakeIO, new Map([[bob, ['bob-device']]]));
    await service.writeMissedCall({ id: 'test-missed', conversationId, caller: { id: alice, name: 'Alice' }, participants: [{ id: alice }, { id: bob, name: 'Bob' }], reason: 'unanswered' });
    assert.equal(await DM.countDocuments({ conversation_id: conversationId, is_missed_call: true }), 1);
    assert.ok(events.some(e => e.name === 'call:missed'));
  });
});
